#!/usr/bin/env bash
# check-pr-body.sh — Fails the build if the active PR body uses bot-style formatting.
# Usage: GH_PR_NUMBER=123 GH_REPO=postil-dev/postil ./scripts/check-pr-body.sh
#   or:  check-pr-body.sh "inline PR body text"
#
# Exit 0 = pass, exit 1 = fail.
set -euo pipefail

# Get the PR body from: argument, GitHub API, or git log (fallback).
body=""

if [ $# -gt 0 ]; then
  body="$1"
elif [ -n "${GH_PR_NUMBER:-}" ] && [ -n "${GH_REPO:-}" ]; then
  body=$(curl -sf "https://api.github.com/repos/${GH_REPO}/pulls/${GH_PR_NUMBER}" \
    | python3 -c "import sys,json;print(json.loads(sys.stdin.read()).get('body','') or '')")
elif [ -n "${PR_BODY:-}" ]; then
  body="$PR_BODY"
fi

if [ -z "$body" ]; then
  echo "check-pr-body: no PR body provided — skipping check."
  exit 0
fi

any_fail=0

# Check for markdown headings
if echo "$body" | grep -qE '^## '; then
  echo "check-pr-body: FAIL — PR body contains markdown headings (## ...)"
  echo "  Write plain prose, no section headers."
  any_fail=1
fi

# Check for checkbox lists
if echo "$body" | grep -qE '^\s*- \[[ x]\] '; then
  echo "check-pr-body: FAIL — PR body contains checkbox lists (- [x] ...)"
  echo "  Use prose instead."
  any_fail=1
fi

# Check for horizontal dividers
if echo "$body" | grep -qE '^---+$'; then
  echo "check-pr-body: FAIL — PR body contains a horizontal divider (---)"
  echo "  Remove it."
  any_fail=1
fi

# Check for generated-by footers
if echo "$body" | grep -qi 'generated by\|auto-generated\|this pr was created'; then
  echo "check-pr-body: FAIL — PR body contains a generated-by footer"
  echo "  Remove it."
  any_fail=1
fi

if [ "$any_fail" -ne 0 ]; then
  echo ""
  echo "check-pr-body: The PR body should be 1-4 sentences of plain prose."
  echo "Good: 'Adds a metrics endpoint at /api/metrics so we can track token spend.'"
  echo "Bad:  '## Summary\nChanges...\n## Test plan\n- [x] verified locally'"
  exit 1
fi

echo "check-pr-body: PASS"